lsp4ij: Add support for Regal language server (#190)
* lsp4ij: Add Regal support

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

* lsp4ij: Show Debug lens

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

* lsp4ij: Add DAP support for Regal

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

* lsp4ij: Add folding, signature help, + doc symbols

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

* lsp4ij: Formatting and tidying

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

* lsp4ji: remove debugging message handling

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

* lsp4ij: README updates

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

* Update plugin to support 2025.3 releases

The main change here to so account for the consolidation of these IDEs into a
single unfied release for each product line.

I was able to test with the latest IDEA and PyCharm too (the ones we had listed
as supported).

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

* Update minimum IDE build version to 252

This has been done to avoid disk space errors on CI

System.IO.IOException: No space left on device

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

* Update lsp4ij dependency

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

* Replace deprecated DAPRunConfigurationOptions

Updates import and method signature to use IntelliJ's base
RunConfigurationOptions class.

Removes dependency on deprecated LSP4IJ DAP-specific configuration options.

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

* Disable LSP and DAP for light tests

Light tests use tempFS which is incompatible with LSP4IJ's
LanguageServerManager and DebugAdapterManager.
Stop the Regal language server and remove the debug adapter during test
setup to prevent initialization failures.

Following comment:

https://github.com/open-policy-agent/opa-idea-plugin/pull/190#issuecomment-3176795485

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

* Add new verifyPluginCI for single IDE check

This check should not overflow the disk on the GHA instance

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

* Use CI var to toggle used IDEs

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

* Update OPA version in readme

This should be the more recent version now

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

* DRY up regal binary finding into shared utility

Consolidate duplicate regal executable search code into RegalExecutableUtil.
Also use IntelliJ's PathEnvironmentVariableUtil and SystemInfo APIs for
cross-platform compatibility.

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

---------

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>
Signed-off-by: Charlie Egan <charlie_egan@apple.com>
Co-authored-by: Charlie Egan <charlieegan3@users.noreply.github.com>